### ISSUE TITLE
Illegal Data Adress ERROR 

### ISSUE THREAD

**Issue by mhrbsl** [ductsoup/Yun-ModbusTK-Example#1]
I tried to call modbus_tcp_slave.py script from arduino IDE and with putty also. The return is,

running...
Initializing 6 RO float registers beginning at 40001
Initializing 6 RW float registers beginning at 40101

When I start polling I get an error ;

('192.168.8.7' 53890 ) is connected with socket 5

Modbus Error: Exception code = 2

Illegal data adress error. When i try to run modbus slave example (by ljean on github) it is working.

Can you help me how can i fix this error ?

**Comment by ductsoup** [comment]
Modbus addressing is tricky business sometimes. There's a very good tutorial from CSI here: [Modbus 101](http://www.csimn.com/CSI_pages/Modbus101.html)
